-- MySQL Script generated by MySQL Workbench
-- Thu May 29 10:50:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`medicamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`medicamento` (
  `id_medicamento` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `precio_minorista` INT NOT NULL,
  `precio_mayorista` VARCHAR(45) NULL,
  `almacenamiento` VARCHAR(45) NOT NULL,
  `via_administración` VARCHAR(45) NOT NULL,
  `efectos_adversos` VARCHAR(45) NOT NULL,
  `requiere_receta` TINYINT NULL,
  PRIMARY KEY (`id_medicamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`droga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`droga` ;

CREATE TABLE IF NOT EXISTS `mydb`.`droga` (
  `id_droga` INT NOT NULL,
  `nombre_droga` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_droga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compuesto_por`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`compuesto_por` ;

CREATE TABLE IF NOT EXISTS `mydb`.`compuesto_por` (
  `medicamento_id_medicamento` INT NOT NULL,
  `droga_id_droga` INT NOT NULL,
  `concentración` INT NOT NULL,
  PRIMARY KEY (`medicamento_id_medicamento`, `droga_id_droga`),
  CONSTRAINT `fk_medicamento_has_droga_medicamento`
    FOREIGN KEY (`medicamento_id_medicamento`)
    REFERENCES `mydb`.`medicamento` (`id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_has_droga_droga1`
    FOREIGN KEY (`droga_id_droga`)
    REFERENCES `mydb`.`droga` (`id_droga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_medicamento_has_droga_droga1_idx` ON `mydb`.`compuesto_por` (`droga_id_droga` ASC) VISIBLE;

CREATE INDEX `fk_medicamento_has_droga_medicamento_idx` ON `mydb`.`compuesto_por` (`medicamento_id_medicamento` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proveedor` (
  `id_proveedor` INT NOT NULL,
  `nombre_proveedor` VARCHAR(45) NOT NULL,
  `CUIT` INT NOT NULL,
  `telefono_proveedor` INT NOT NULL,
  `email_proveedor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lote_droga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`lote_droga` ;

CREATE TABLE IF NOT EXISTS `mydb`.`lote_droga` (
  `id_Lote_Droga` INT NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `fecha_ingreso_lote_droga` DATE NOT NULL,
  `estado` TINYINT NOT NULL,
  `droga_id_droga` INT NOT NULL,
  `proveedor_id_proveedor` INT NOT NULL,
  PRIMARY KEY (`id_Lote_Droga`, `droga_id_droga`, `proveedor_id_proveedor`),
  CONSTRAINT `fk_lote_droga_droga1`
    FOREIGN KEY (`droga_id_droga`)
    REFERENCES `mydb`.`droga` (`id_droga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lote_droga_proveedor1`
    FOREIGN KEY (`proveedor_id_proveedor`)
    REFERENCES `mydb`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_lote_droga_droga1_idx` ON `mydb`.`lote_droga` (`droga_id_droga` ASC) VISIBLE;

CREATE INDEX `fk_lote_droga_proveedor1_idx` ON `mydb`.`lote_droga` (`proveedor_id_proveedor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`lote_medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`lote_medicamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`lote_medicamento` (
  `id_lote_medicamento` INT NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `medicamento_id_medicamento` INT NOT NULL,
  PRIMARY KEY (`id_lote_medicamento`, `medicamento_id_medicamento`),
  CONSTRAINT `fk_lote_medicamento_medicamento1`
    FOREIGN KEY (`medicamento_id_medicamento`)
    REFERENCES `mydb`.`medicamento` (`id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_lote_medicamento_medicamento1_idx` ON `mydb`.`lote_medicamento` (`medicamento_id_medicamento` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`analisis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`analisis` ;

CREATE TABLE IF NOT EXISTS `mydb`.`analisis` (
  `Id_Analisis` INT NOT NULL,
  `tipo_analisis` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Analisis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id_cliente` INT NOT NULL,
  `nombre_cliente` VARCHAR(45) NOT NULL,
  `apellido_cliente` VARCHAR(45) NOT NULL,
  `tipo_cliente` VARCHAR(45) NOT NULL,
  `telefono_cliente` INT NOT NULL,
  `dirección_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`venta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`venta` (
  `id_venta` INT NOT NULL,
  `Fecha_Venta` DATE NOT NULL,
  `Total_Venta` INT NOT NULL,
  `Forma_De_Pago` VARCHAR(45) NOT NULL,
  `Cantidad` INT NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_venta`, `cliente_id_cliente`),
  CONSTRAINT `fk_venta_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_venta_cliente1_idx` ON `mydb`.`venta` (`cliente_id_cliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`contiene`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contiene` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contiene` (
  `lote_medicamento_id_lote_medicamento` INT NOT NULL,
  `lote_medicamento_medicamento_id_medicamento` INT NOT NULL,
  `venta_id_venta` INT NOT NULL,
  `venta_cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`lote_medicamento_id_lote_medicamento`, `lote_medicamento_medicamento_id_medicamento`, `venta_id_venta`, `venta_cliente_id_cliente`),
  CONSTRAINT `fk_lote_medicamento_has_venta_lote_medicamento1`
    FOREIGN KEY (`lote_medicamento_id_lote_medicamento` , `lote_medicamento_medicamento_id_medicamento`)
    REFERENCES `mydb`.`lote_medicamento` (`id_lote_medicamento` , `medicamento_id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lote_medicamento_has_venta_venta1`
    FOREIGN KEY (`venta_id_venta` , `venta_cliente_id_cliente`)
    REFERENCES `mydb`.`venta` (`id_venta` , `cliente_id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_lote_medicamento_has_venta_venta1_idx` ON `mydb`.`contiene` (`venta_id_venta` ASC, `venta_cliente_id_cliente` ASC) VISIBLE;

CREATE INDEX `fk_lote_medicamento_has_venta_lote_medicamento1_idx` ON `mydb`.`contiene` (`lote_medicamento_id_lote_medicamento` ASC, `lote_medicamento_medicamento_id_medicamento` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`analisis_medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`analisis_medicamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`analisis_medicamento` (
  `lote_medicamento_id_lote_medicamento` INT NOT NULL,
  `lote_medicamento_medicamento_id_medicamento` INT NOT NULL,
  `analisis_Id_Analisis` INT NOT NULL,
  `resultado_m` VARCHAR(45) NOT NULL,
  `fecha_analisis_m` DATE NOT NULL,
  PRIMARY KEY (`lote_medicamento_id_lote_medicamento`, `lote_medicamento_medicamento_id_medicamento`, `analisis_Id_Analisis`),
  CONSTRAINT `fk_lote_medicamento_has_analisis_lote_medicamento1`
    FOREIGN KEY (`lote_medicamento_id_lote_medicamento` , `lote_medicamento_medicamento_id_medicamento`)
    REFERENCES `mydb`.`lote_medicamento` (`id_lote_medicamento` , `medicamento_id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lote_medicamento_has_analisis_analisis1`
    FOREIGN KEY (`analisis_Id_Analisis`)
    REFERENCES `mydb`.`analisis` (`Id_Analisis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_lote_medicamento_has_analisis_analisis1_idx` ON `mydb`.`analisis_medicamento` (`analisis_Id_Analisis` ASC) VISIBLE;

CREATE INDEX `fk_lote_medicamento_has_analisis_lote_medicamento1_idx` ON `mydb`.`analisis_medicamento` (`lote_medicamento_id_lote_medicamento` ASC, `lote_medicamento_medicamento_id_medicamento` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`table1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`analisis_d`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`analisis_d` ;

CREATE TABLE IF NOT EXISTS `mydb`.`analisis_d` (
  `analisis_Id_Analisis` INT NOT NULL,
  `lote_droga_id_Lote_Droga` INT NOT NULL,
  `lote_droga_droga_id_droga` INT NOT NULL,
  `lote_droga_proveedor_id_proveedor` INT NOT NULL,
  `resultado_d` VARCHAR(45) NOT NULL,
  `fecha_analisis_d` DATE NOT NULL,
  PRIMARY KEY (`analisis_Id_Analisis`, `lote_droga_id_Lote_Droga`, `lote_droga_droga_id_droga`, `lote_droga_proveedor_id_proveedor`),
  CONSTRAINT `fk_analisis_has_lote_droga_analisis1`
    FOREIGN KEY (`analisis_Id_Analisis`)
    REFERENCES `mydb`.`analisis` (`Id_Analisis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_analisis_has_lote_droga_lote_droga1`
    FOREIGN KEY (`lote_droga_id_Lote_Droga` , `lote_droga_droga_id_droga` , `lote_droga_proveedor_id_proveedor`)
    REFERENCES `mydb`.`lote_droga` (`id_Lote_Droga` , `droga_id_droga` , `proveedor_id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_analisis_has_lote_droga_lote_droga1_idx` ON `mydb`.`analisis_d` (`lote_droga_id_Lote_Droga` ASC, `lote_droga_droga_id_droga` ASC, `lote_droga_proveedor_id_proveedor` ASC) VISIBLE;

CREATE INDEX `fk_analisis_has_lote_droga_analisis1_idx` ON `mydb`.`analisis_d` (`analisis_Id_Analisis` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

